database:
  name: tinylog
  host: 127.0.0.1
  port: 3306
  username: root
  password:
  logging: true

cache:
  host: 127.0.0.1
  port: 6379
  db: 0

zookeeper: 127.0.0.1:2181

jwt:
  secret: 8tma9c55apv1yhds
  exp: 2592000  # 30 day

mq:
  host: 127.0.0.1
  port: 9092

env: development
port: 8080
